### ISSUE TITLE
pymc-learn fails with a theano error

### ISSUE THREAD

**Issue by sreedta8** [pymc-learn/pymc-learn#46]
Hi 

First time trying to install and use ```pymc-learn``` on a ```Windows10, Anaconda, pymc (latest stable)``` environment

Here are the commands I ran and the error I get from the ```pymc-learn``` quick start guide:

```
(pymc_learn) C:\Users\sreedatta>python
Python 3.10.2 | packaged by conda-forge | (main, Jan 14 2022, 07:58:58) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from sklearn.datasets import make_friedman2
>>> from pmlearn.gaussian_process import GaussianProcessRegressor
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
The imported Theano(-PyMC) module is broken.
It was imported from _NamespacePath(['C:\\Users\\sreedatta\\Anaconda3\\envs\\pymc_learn\\lib\\site-packages\\theano'])
Try to uninstall/reinstall it after closing all active sessions/notebooks.
Also see https://github.com/pymc-devs/pymc3/wiki for installation instructions.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\sreedatta\Anaconda3\envs\pymc_learn\lib\site-packages\pmlearn\gaussian_process\__init__.py", line 12, in <module>
    from .gpr import GaussianProcessRegressor
  File "C:\Users\sreedatta\Anaconda3\envs\pymc_learn\lib\site-packages\pmlearn\gaussian_process\gpr.py", line 8, in <module>
    import pymc3 as pm
  File "C:\Users\sreedatta\Anaconda3\envs\pymc_learn\lib\site-packages\pymc3\__init__.py", line 79, in <module>
    __set_compiler_flags()
  File "C:\Users\sreedatta\Anaconda3\envs\pymc_learn\lib\site-packages\pymc3\__init__.py", line 61, in __set_compiler_flags
    current = theano.config.gcc__cxxflags
AttributeError: module 'theano' has no attribute 'config'
```

Here is my environment setup (conda list output) for ```pymc-learn```:

```
# Name                    Version                   Build  Channel
alabaster                 0.7.12                   pypi_0    pypi
arviz                     0.11.4             pyhd8ed1ab_0    conda-forge
babel                     2.9.1                    pypi_0    pypi
brotli                    1.0.9                h8ffe710_6    conda-forge
brotli-bin                1.0.9                h8ffe710_6    conda-forge
bzip2                     1.0.8                h8ffe710_4    conda-forge
ca-certificates           2021.10.8            h5b45459_0    conda-forge
cachetools                5.0.0                    pypi_0    pypi
cairo                     1.16.0            h15b3021_1009    conda-forge
certifi                   2021.10.8       py310h5588dad_1    conda-forge
cftime                    1.5.1.1         py310h2873277_1    conda-forge
charset-normalizer        2.0.10                   pypi_0    pypi
colorama                  0.4.4                    pypi_0    pypi
curl                      7.81.0               h789b8ee_0    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
dill                      0.3.4                    pypi_0    pypi
docutils                  0.17.1                   pypi_0    pypi
expat                     2.4.3                h39d44d4_0    conda-forge
fastprogress              1.0.0                    pypi_0    pypi
filelock                  3.4.2                    pypi_0    pypi
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.13.1            h1989441_1005    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fonttools                 4.28.5          py310he2412df_0    conda-forge
freetype                  2.10.4               h546665d_1    conda-forge
fribidi                   1.0.10               h8d14728_0    conda-forge
future                    0.18.2                   pypi_0    pypi
getopt-win32              0.1                  h8ffe710_0    conda-forge
gettext                   0.19.8.1          ha2e2712_1008    conda-forge
graphite2                 1.3.13                     1000    conda-forge
graphviz                  2.50.0               had6c3a3_2    conda-forge
gts                       0.7.6                h7c369d9_2    conda-forge
harfbuzz                  3.2.0                hc1763ed_0    conda-forge
hdf4                      4.2.15               h0e5069d_3    conda-forge
hdf5                      1.12.1          nompi_h57737ce_103    conda-forge
icu                       69.1                 h0e60522_0    conda-forge
idna                      3.3                      pypi_0    pypi
imagesize                 1.3.0                    pypi_0    pypi
importlib-metadata        4.10.1          py310h5588dad_0    conda-forge
importlib_metadata        4.10.1               hd8ed1ab_0    conda-forge
intel-openmp              2022.0.0          h57928b3_3663    conda-forge
jbig                      2.1               h8d14728_2003    conda-forge
jinja2                    3.0.3                    pypi_0    pypi
joblib                    1.1.0                    pypi_0    pypi
jpeg                      9d                   h8ffe710_0    conda-forge
kiwisolver                1.3.2           py310h476a331_1    conda-forge
krb5                      1.19.2               h6da9e4a_3    conda-forge
lcms2                     2.12                 h2a16943_0    conda-forge
lerc                      3.0                  h0e60522_0    conda-forge
libblas                   3.9.0              12_win64_mkl    conda-forge
libbrotlicommon           1.0.9                h8ffe710_6    conda-forge
libbrotlidec              1.0.9                h8ffe710_6    conda-forge
libbrotlienc              1.0.9                h8ffe710_6    conda-forge
libcblas                  3.9.0              12_win64_mkl    conda-forge
libcurl                   7.81.0               h789b8ee_0    conda-forge
libdeflate                1.8                  h8ffe710_0    conda-forge
libffi                    3.4.2                h8ffe710_5    conda-forge
libgd                     2.3.3                h217ff3b_1    conda-forge
libglib                   2.70.2               h3be07f2_1    conda-forge
libiconv                  1.16                 he774522_0    conda-forge
liblapack                 3.9.0              12_win64_mkl    conda-forge
libnetcdf                 4.8.1           nompi_h1cc8e9d_101    conda-forge
libpng                    1.6.37               h1d00b33_2    conda-forge
libpython                 2.1             py310h5588dad_1    conda-forge
libssh2                   1.10.0               h9a1e1f7_2    conda-forge
libtiff                   4.3.0                hd413186_2    conda-forge
libwebp                   1.2.1                h57928b3_0    conda-forge
libwebp-base              1.2.1                h8ffe710_0    conda-forge
libxcb                    1.13              hcd874cb_1004    conda-forge
libxml2                   2.9.12               hf5bbc77_1    conda-forge
libzip                    1.8.0                h519de47_1    conda-forge
libzlib                   1.2.11            h8ffe710_1013    conda-forge
llvmlite                  0.38.0          py310h2c03ce5_0    conda-forge
lz4-c                     1.9.3                h8ffe710_1    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
markupsafe                2.0.1                    pypi_0    pypi
matplotlib-base           3.5.1           py310h79a7439_0    conda-forge
mkl                       2021.4.0           h0e2418a_729    conda-forge
mkl-service               2.4.0           py310hcf6e17e_0    conda-forge
msys2-conda-epoch         20160418                      1    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
netcdf4                   1.5.8           nompi_py310h5489b47_101    conda-forge
numba                     0.55.0          py310h77579ad_0    conda-forge
numpy                     1.21.5          py310hcae7c84_0    conda-forge
numpydoc                  1.1.0                    pypi_0    pypi
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openjpeg                  2.4.0                hb211442_1    conda-forge
openssl                   3.0.0                h8ffe710_2    conda-forge
packaging                 21.3               pyhd8ed1ab_0    conda-forge
pandas                    1.3.5           py310hf5e1058_0    conda-forge
pango                     1.50.3               h6a11761_0    conda-forge
patsy                     0.5.2                    pypi_0    pypi
pcre                      8.45                 h0e60522_0    conda-forge
pillow                    8.4.0           py310h22f3323_0    conda-forge
pip                       21.3.1             pyhd8ed1ab_0    conda-forge
pixman                    0.40.0               h8ffe710_0    conda-forge
pthread-stubs             0.4               hcd874cb_1001    conda-forge
pygments                  2.11.2                   pypi_0    pypi
pymc-learn                0.0.1rc3                 pypi_0    pypi
pymc3                     3.11.4                   pypi_0    pypi
pyparsing                 3.0.6              pyhd8ed1ab_0    conda-forge
python                    3.10.2          hcf16a7b_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-graphviz           0.19.1             pyhaef67bd_0    conda-forge
python_abi                3.10                    2_cp310    conda-forge
pytz                      2021.3             pyhd8ed1ab_0    conda-forge
requests                  2.27.1                   pypi_0    pypi
scikit-learn              1.0.2                    pypi_0    pypi
scipy                     1.7.3           py310h33db832_0    conda-forge
seaborn                   0.11.2                   pypi_0    pypi
semver                    2.13.0                   pypi_0    pypi
setuptools                59.8.0          py310h5588dad_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
snowballstemmer           2.2.0                    pypi_0    pypi
sphinx                    4.4.0                    pypi_0    pypi
sphinxcontrib-applehelp   1.0.2                    pypi_0    pypi
sphinxcontrib-devhelp     1.0.2                    pypi_0    pypi
sphinxcontrib-htmlhelp    2.0.0                    pypi_0    pypi
sphinxcontrib-jsmath      1.0.1                    pypi_0    pypi
sphinxcontrib-qthelp      1.0.3                    pypi_0    pypi
sphinxcontrib-serializinghtml 1.1.5                    pypi_0    pypi
sqlite                    3.37.0               h8ffe710_0    conda-forge
tbb                       2021.5.0             h2d74725_0    conda-forge
theano-pymc               1.1.2                    pypi_0    pypi
threadpoolctl             3.0.0                    pypi_0    pypi
tk                        8.6.11               h8ffe710_1    conda-forge
tqdm                      4.62.3                   pypi_0    pypi
typing_extensions         3.10.0.2           pyha770c72_0    conda-forge
tzdata                    2021e                he74cb21_0    conda-forge
ucrt                      10.0.20348.0         h57928b3_0    conda-forge
urllib3                   1.26.8                   pypi_0    pypi
vc                        14.2                 hb210afc_6    conda-forge
vs2015_runtime            14.29.30037          h902a5da_6    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xarray                    0.20.2             pyhd8ed1ab_0    conda-forge
xorg-kbproto              1.0.7             hcd874cb_1002    conda-forge
xorg-libice               1.0.10               hcd874cb_0    conda-forge
xorg-libsm                1.2.3             hcd874cb_1000    conda-forge
xorg-libx11               1.7.2                hcd874cb_0    conda-forge
xorg-libxau               1.0.9                hcd874cb_0    conda-forge
xorg-libxdmcp             1.1.3                hcd874cb_0    conda-forge
xorg-libxext              1.3.4                hcd874cb_1    conda-forge
xorg-libxpm               3.5.13               hcd874cb_0    conda-forge
xorg-libxt                1.2.1                hcd874cb_2    conda-forge
xorg-xextproto            7.3.0             hcd874cb_1002    conda-forge
xorg-xproto               7.0.31            hcd874cb_1007    conda-forge
xz                        5.2.5                h62dcd97_1    conda-forge
zipp                      3.7.0              pyhd8ed1ab_0    conda-forge
zlib                      1.2.11            h8ffe710_1013    conda-forge
zstd                      1.5.1                h6255e5f_0    conda-forge
```

**Comment by sreedat** [comment]
I was able to resolve the above ```Theano``` error after understanding the ```requirements``` file which showed that ```pymc-learn``` is best suited to work with ```pymc3=3.4.1``` and ```python=3.6```

I did a complete new install following the ```requirements``` specs as closely as possible and I was able to replicate "ADVI" based portions of the Linear Regression example hosted here:  https://hub.gke2.mybinder.org/user/pymc-learn-pymc-learn-zaedy52s/notebooks/docs/notebooks/LinearRegression.ipynb

I have found some code errors and corrected them. I will post these corrections separately. What I need help with is the error I run into when I try run the Linear Regression using ```NUTS``` sampler. 

Here is my Conda list output for the new environment:

```
# Name                    Version                   Build  Channel
alabaster                 0.7.12                   pypi_0    pypi
argon2-cffi               21.1.0           py36h68aa20f_0    conda-forge
async_generator           1.10                       py_0    conda-forge
attrs                     21.4.0             pyhd8ed1ab_0    conda-forge
babel                     2.9.1                    pypi_0    pypi
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
bleach                    4.1.0              pyhd8ed1ab_0    conda-forge
cached-property           1.5.2                    pypi_0    pypi
certifi                   2021.10.8                pypi_0    pypi
cffi                      1.14.6           py36he58ceb7_1    conda-forge
charset-normalizer        2.0.10                   pypi_0    pypi
colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
cycler                    0.11.0                   pypi_0    pypi
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
dill                      0.3.4                    pypi_0    pypi
docutils                  0.17.1                   pypi_0    pypi
entrypoints               0.3             pyhd8ed1ab_1003    conda-forge
future                    0.18.2                   pypi_0    pypi
h5py                      3.1.0                    pypi_0    pypi
idna                      3.3                      pypi_0    pypi
imagesize                 1.3.0                    pypi_0    pypi
importlib-metadata        4.8.3                    pypi_0    pypi
intel-openmp              2021.4.0          h57928b3_3556    conda-forge
ipykernel                 5.5.5            py36hfacbf0b_0    conda-forge
ipython                   7.16.1           py36h7b2dad6_2    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
jedi                      0.17.2           py36ha15d459_1    conda-forge
jinja2                    3.0.3              pyhd8ed1ab_0    conda-forge
joblib                    1.1.0                    pypi_0    pypi
jsonschema                4.1.2              pyhd8ed1ab_0    conda-forge
jupyter_client            7.1.1              pyhd8ed1ab_0    conda-forge
jupyter_core              4.8.1            py36ha15d459_0    conda-forge
jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
kiwisolver                1.3.1                    pypi_0    pypi
libblas                   3.9.0           5_hd5c7e75_netlib    conda-forge
libcblas                  3.9.0           5_hd5c7e75_netlib    conda-forge
liblapack                 3.9.0           5_hd5c7e75_netlib    conda-forge
libpython                 2.1              py36ha15d459_0    conda-forge
libsodium                 1.0.18               h8d14728_1    conda-forge
libzlib                   1.2.11            h8ffe710_1013    conda-forge
llvmlite                  0.36.0           py36haecd60e_0    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
markupsafe                2.0.1            py36h68aa20f_0    conda-forge
matplotlib                3.3.4                    pypi_0    pypi
mistune                   0.8.4           py36h68aa20f_1004    conda-forge
mkl                       2021.4.0           haa95532_640
mkl-service               2.4.0            py36h68aa20f_0    conda-forge
msys2-conda-epoch         20160418                      1    conda-forge
nbclient                  0.5.9              pyhd8ed1ab_0    conda-forge
nbconvert                 6.0.7            py36ha15d459_3    conda-forge
nbformat                  5.1.3              pyhd8ed1ab_0    conda-forge
nest-asyncio              1.5.4              pyhd8ed1ab_0    conda-forge
notebook                  6.3.0            py36ha15d459_0    conda-forge
numba                     0.53.1           py36hd0dfabe_1    conda-forge
numpy                     1.19.5           py36h4b40d73_2    conda-forge
numpydoc                  1.1.0                    pypi_0    pypi
packaging                 21.3               pyhd8ed1ab_0    conda-forge
pandas                    1.1.5                    pypi_0    pypi
pandoc                    2.17.0.1             h8ffe710_0    conda-forge
pandocfilters             1.5.0              pyhd8ed1ab_0    conda-forge
parso                     0.7.1              pyh9f0ad1d_0    conda-forge
patsy                     0.5.2                    pypi_0    pypi
picklejar                 2.1.2                    pypi_0    pypi
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    8.4.0                    pypi_0    pypi
pip                       21.3.1             pyhd8ed1ab_0    conda-forge
prometheus_client         0.12.0             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.24             pyha770c72_0    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pygments                  2.11.2             pyhd8ed1ab_0    conda-forge
pymc-learn                0.0.1rc3                 pypi_0    pypi
pymc3                     3.4.1                    pypi_0    pypi
pyparsing                 3.0.6              pyhd8ed1ab_0    conda-forge
pyrsistent                0.17.3           py36h68aa20f_2    conda-forge
python                    3.6.15          h39d44d4_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.6                     2_cp36m    conda-forge
pytz                      2021.3                   pypi_0    pypi
pywin32                   301              py36h68aa20f_0    conda-forge
pywinpty                  1.1.4            py36hcae0e51_0    conda-forge
pyzmq                     22.3.0           py36h1d5d788_0    conda-forge
requests                  2.27.1                   pypi_0    pypi
scikit-learn              0.24.2                   pypi_0    pypi
scipy                     1.5.4                    pypi_0    pypi
seaborn                   0.11.2                   pypi_0    pypi
send2trash                1.8.0              pyhd8ed1ab_0    conda-forge
setuptools                58.0.4           py36ha15d459_2    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
snowballstemmer           2.2.0                    pypi_0    pypi
sphinx                    4.4.0                    pypi_0    pypi
sphinxcontrib-applehelp   1.0.2                    pypi_0    pypi
sphinxcontrib-devhelp     1.0.2                    pypi_0    pypi
sphinxcontrib-htmlhelp    2.0.0                    pypi_0    pypi
sphinxcontrib-jsmath      1.0.1                    pypi_0    pypi
sphinxcontrib-qthelp      1.0.3                    pypi_0    pypi
sphinxcontrib-serializinghtml 1.1.5                    pypi_0    pypi
terminado                 0.12.1           py36ha15d459_0    conda-forge
testpath                  0.5.0              pyhd8ed1ab_0    conda-forge
theano                    1.0.5                    pypi_0    pypi
threadpoolctl             3.0.0                    pypi_0    pypi
tornado                   6.1              py36h68aa20f_1    conda-forge
tqdm                      4.62.3                   pypi_0    pypi
traitlets                 4.3.3              pyhd8ed1ab_2    conda-forge
typing_extensions         4.0.1              pyha770c72_0    conda-forge
ucrt                      10.0.20348.0         h57928b3_0    conda-forge
urllib3                   1.26.8                   pypi_0    pypi
vc                        14.2                 hb210afc_6    conda-forge
vs2015_runtime            14.29.30037          h902a5da_6    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
winpty                    0.4.3                         4    conda-forge
zeromq                    4.3.4                h0e60522_1    conda-forge
zipp                      3.6.0                    pypi_0    pypi
zlib                      1.2.11            h8ffe710_1013    conda-forge
```

Here is the complete error output:
```
Exception: ('Compilation failed (return status=1): C:\\Users\\sreedatta\\AppData\\Local\\Temp\\cc0YzZTj.s: Assembler messages:\r. C:\\Users\\sreedatta\\AppData\\Local\\Temp\\cc0YzZTj.s:365: Error: invalid register for .seh_savexmm\r. C:\\Users\\sreedatta\\AppData\\Local\\Temp\\cc0YzZTj.s:367: Error: invalid register for .seh_savexmm\r. C:\\Users\\sreedatta\\AppData\\Local\\Temp\\cc0YzZTj.s:369: Error: invalid register for .seh_savexmm\r. C:\\Users\\sreedatta\\AppData\\Local\\Temp\\cc0YzZTj.s:371: Error: invalid register for .seh_savexmm\r. C:\\Users\\sreedatta\\AppData\\Local\\Temp\\cc0YzZTj.s:373: Error: invalid register for .seh_savexmm\r. C:\\Users\\sreedatta\\AppData\\Local\\Temp\\cc0YzZTj.s:375: Error: invalid register for .seh_savexmm\r. C:\\Users\\sreedatta\\AppData\\Local\\Temp\\cc0YzZTj.s:377: Error: invalid register for .seh_savexmm\r. C:\\Users\\sreedatta\\AppData\\Local\\Temp\\cc0YzZTj.s:379: Error: invalid register for .seh_savexmm\r. C:\\Users\\sreedatta\\AppData\\Local\\Temp\\cc0YzZTj.s:381: Error: invalid register for .seh_savexmm\r. C:\\Users\\sreedatta\\AppData\\Local\\Temp\\cc0YzZTj.s:383: Error: invalid register for .seh_savexmm\r. C:\\Users\\sreedatta\\AppData\\Local\\Temp\\cc0YzZTj.s:385: Error: invalid register for .seh_savexmm\r. C:\\Users\\sreedatta\\AppData\\Local\\Temp\\cc0YzZTj.s:387: Error: invalid register for .seh_savexmm\r. C:\\Users\\sreedatta\\AppData\\Local\\Temp\\cc0YzZTj.s:389: Error: invalid register for .seh_savexmm\r. C:\\Users\\sreedatta\\AppData\\Local\\Temp\\cc0YzZTj.s:391: Error: invalid register for .seh_savexmm\r. C:\\Users\\sreedatta\\AppData\\Local\\Temp\\cc0YzZTj.s:393: Error: invalid register for .seh_savexmm\r. C:\\Users\\sreedatta\\AppData\\Local\\Temp\\cc0YzZTj.s:395: Error: invalid register for .seh_savexmm\r. ', '[Elemwise{mul}(<TensorType(float64, (True,))>, <TensorType(int8, (True,))>)]')
```

Can one of you let me know how to correct this error?

Sri

**Comment by sreedat** [comment]
Additional information about the above error: I had seen this error arise when working with ```pymc3``` and the ```gcc``` compiler was not the correct one. So I tested the following versions of ```gcc``` MSYS2 compilers outside Anaconda: 5.3.0, 5.4.0, 7.3.0, 8.3.0, and 11.2.0. Then I tested with the version 5.3.0 version of the ```gcc``` that comes from Anaconda itself using the package/library ```m2w64-toolchain```. The error persists.

Any help would be appreciated
